openapi: 3.0.3
info:
  title: Guessify API
  version: 1.0.0
  description: API specification for Guessify game backend.

paths:
  /api/rooms:
    post:
      summary: Create a new game room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateRoomRequest"
      responses:
        "200":
          description: Created room
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RoomCreatedResponse"

  /api/rooms/join:
    post:
      summary: Join an existing room
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/JoinRoomRequest"
      responses:
        "200":
          description: Successfully joined room
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JoinRoomResponse"

  /api/rooms/{roomId}/players:
    get:
      summary: Get list of players in a room
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: List of players
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Player"

  /api/games/{gameId}/submit:
    post:
      summary: Submit final score for a player
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SubmitScoreRequest"
      responses:
        "200":
          description: Score submitted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitScoreResponse"

  /api/games/{gameId}/results:
    get:
      summary: Get current results or final leaderboard
      parameters:
        - name: gameId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Game results status or leaderboard
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameResultsResponse"

components:
  schemas:
    CreateRoomRequest:
      type: object
      properties:
        hostName:
          type: string
        maxPlayers:
          type: integer
        songSource:
          type: string
          enum: [SPOTIFY, HOST, PLAYERS]
        gameMode:
          type: string
          enum: [TITLE, AUTHOR, USER]
        answerTimeSeconds:
          type: number
        roundsNumber:
          type: integer
        playbackLength:
          type: number
        roomPasswordHash:
          type: string

    RoomCreatedResponse:
      type: object
      properties:
        roomId:
          type: string
        roomCode:
          type: string

    JoinRoomRequest:
      type: object
      properties:
        roomId:
          type: string
        password:
          type: string
        userId:
          type: integer

    JoinRoomResponse:
      type: object
      properties:
        status:
          type: string
        player:
          $ref: "#/components/schemas/Player"

    Player:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        avatarUrl:
          type: string

    SubmitScoreRequest:
      type: object
      required:
        - playerId
        - score
      properties:
        playerId:
          type: string
        score:
          type: integer

    SubmitScoreResponse:
      type: object
      properties:
        status:
          type: string
          enum: [ok]

    GameResultsResponse:
      type: object
      properties:
        status:
          type: string
          enum: [waiting, complete]
        playersRemaining:
          type: integer
          nullable: true
        leaderboard:
          type: array
          nullable: true
          items:
            $ref: "#/components/schemas/LeaderboardEntry"

    LeaderboardEntry:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        score:
          type: integer
